const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call fake spaghetti? An impasta!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "Why did the orange stop? It ran out of juice.",
  "What do you call a fish with no eyes? Fsh!",
  "Why was the broom late? It swept in.",
  "What do you get when you cross a cow and a duck? Milk and quackers!",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the computer go to the doctor? Because it had a virus!",
  "What do you get if you cross an elephant and a rhino? Elephino!",
  "Why don't seagulls fly over the bay? Because then they'd be bagels!",
  "Why do cows have hooves instead of feet? Because they lactose.",
  "Why was the math book always worried? It had too many problems.",
  "Why do fish live in saltwater? Because pepper makes them sneeze!",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What do you get when you cross a snowman and a dog? Frostbite!",
  "Why did the chicken go to the seance? To talk to the other side.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the bicycle fall over? It was two-tired.",
  "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why did the computer go to the doctor? It had a virus.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you get when you cross a cow and a duck? Milk and quackers.",
  "Why was the broom late? It swept in.",
  "What do you call a fish with no eyes? Fsh.",
  "Why did the orange stop? It ran out of juice.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call fake spaghetti? An impasta.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the chicken join a band? Because it had the drumsticks.",
  "Why don't programmers like nature? It has too many bugs.",
  "Why do cows wear bells? Because their horns don't work.",
  "What do you call a pile of cats? A meowtain.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
  "Why don't skeletons play music in church? They don't have any organs.",
  "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels!",
  "Why was the math book sad? It had too many problems.",
  "Why do fish live in saltwater? Because pepper makes them sneeze.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "Why don't sharks eat clowns? Because they taste funny.",
  "What do you call a lazy kangaroo? A pouch potato.",
  "Why don't some fish do well in school? Because they can't work well in schools.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field.",
  "Why did the computer keep sneezing? It had a virus.",
  "Why don't ants get sick? Because they have tiny ant-bodies.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "Why was the math book always worried? It had too many problems.",
  "Why don't seagulls fly over the bay? Because then they'd be bagels!",
  "Why do cows have hooves instead of feet? Because they lactose.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call an alligator in a vest? An investigator.",
  "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
  "Why do fish live in saltwater? Because pepper makes them sneeze.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "Why don't sharks eat clowns? Because they taste funny.",
  "What do you call fake spaghetti? An impasta.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you get when you cross a cow and a duck? Milk and quackers.",
  "Why did the computer go to the doctor? It had a virus.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why was the broom late? It swept in.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a fish with no eyes? Fsh.",
  "Why did the orange stop? It ran out of juice.",
  "What do you call cheese that isn't yours? Nacho cheese.",
];

module.exports = jokes;
